name: pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - tensorboard
  - jupyterlab
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - h5py
  - numba
  - requests
  - psutil
  - future
  - memory_profiler
  - pip
  - pip:
    - torchsummary
    - cmake
    - MulticoreTSNE-modified
    - umap-learn
    - pyspark
    - ray
    - gputil