# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: GT CS7641 Project3 - Semi-supervised Image-to-image Translation
title: GT CS7641 SP2020 Project - Team3 Learning Machines<p align="center">Domain Adaptation<br>via<br>Semi-supervised Image-to-image Translation</p>
email: stan84@gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
  <span style="color:aqua">
  ABSTRACT<br>
  Generalization is an important aspect of machine learning algorithms
  to handle unseen data and to make correct prediction on them on running time.
  However, it is often difficult to train a supervised model,
  especially for a classification task,
  when there is a lack of labels for the new data.
  On the other hand, acquiring a set of accurate labels for a new dataset
  is often challenging since the process is mostly time and labor-intensive.
  In this project, we propose a (semi-)supervised image-to-image translation framework as a domain adaptation method
  based on a combination of variational autoencoders and generative adversarial networks upon a shared latent space assumption.
  The proposed framework is able to effectively translate target domain images to source domain images,
  which can be directly classified into the matched classes.
  Experimental results show that stable translations as well as classification accuracy higher than baseline models
  can be achieved even with a small amount of labels for the target domain data.
  </span>
baseurl: "/semit" # the subpath of your site, e.g. /blog
url: "https://ast0414.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: ast0414

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
